services:
  # AI Service (Python)
  - name: gowhere-ai
    type: web
    env: python
    rootDir: ./ai
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn ai.api:app --host 0.0.0.0 --port $PORT"
    
  # Backend Service (Node.js)
  - name: gowhere-backend
    type: web
    env: node
    rootDir: ./backend
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: AI_SERVICE_HOST # Provide the host of the AI service
        fromService:
          type: web
          name: gowhere-ai
          property: host # 'host' is a valid property
